name: ci

on: 
  push:
    branches: 
      - master

jobs:
  test:
    name: Build and push
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build image
        run:
          Docker build .







           
