name: Build a docker image and push it to AWS ECR
on: [push]

jobs:
  test:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: action/checkout@v2

      - name: Build image
        run:
          Docker build .
           
